// Generated by gencpp from file teleop/robotcmd.msg
// DO NOT EDIT!


#ifndef TELEOP_MESSAGE_ROBOTCMD_H
#define TELEOP_MESSAGE_ROBOTCMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace teleop
{
template <class ContainerAllocator>
struct robotcmd_
{
  typedef robotcmd_<ContainerAllocator> Type;

  robotcmd_()
    : drive_fvel(0.0)
    , drive_rvel(0.0)
    , flipper(0.0)  {
    }
  robotcmd_(const ContainerAllocator& _alloc)
    : drive_fvel(0.0)
    , drive_rvel(0.0)
    , flipper(0.0)  {
  (void)_alloc;
    }



   typedef float _drive_fvel_type;
  _drive_fvel_type drive_fvel;

   typedef float _drive_rvel_type;
  _drive_rvel_type drive_rvel;

   typedef float _flipper_type;
  _flipper_type flipper;




  typedef boost::shared_ptr< ::teleop::robotcmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::teleop::robotcmd_<ContainerAllocator> const> ConstPtr;

}; // struct robotcmd_

typedef ::teleop::robotcmd_<std::allocator<void> > robotcmd;

typedef boost::shared_ptr< ::teleop::robotcmd > robotcmdPtr;
typedef boost::shared_ptr< ::teleop::robotcmd const> robotcmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::teleop::robotcmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::teleop::robotcmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace teleop

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'teleop': ['/home/austin/combot/src/teleop/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::teleop::robotcmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::teleop::robotcmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::teleop::robotcmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::teleop::robotcmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::teleop::robotcmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::teleop::robotcmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::teleop::robotcmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "04e0164496b5b11175b5eb32f5fde4f5";
  }

  static const char* value(const ::teleop::robotcmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x04e0164496b5b111ULL;
  static const uint64_t static_value2 = 0x75b5eb32f5fde4f5ULL;
};

template<class ContainerAllocator>
struct DataType< ::teleop::robotcmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "teleop/robotcmd";
  }

  static const char* value(const ::teleop::robotcmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::teleop::robotcmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 drive_fvel\n\
float32 drive_rvel\n\
float32 flipper\n\
";
  }

  static const char* value(const ::teleop::robotcmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::teleop::robotcmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.drive_fvel);
      stream.next(m.drive_rvel);
      stream.next(m.flipper);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct robotcmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::teleop::robotcmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::teleop::robotcmd_<ContainerAllocator>& v)
  {
    s << indent << "drive_fvel: ";
    Printer<float>::stream(s, indent + "  ", v.drive_fvel);
    s << indent << "drive_rvel: ";
    Printer<float>::stream(s, indent + "  ", v.drive_rvel);
    s << indent << "flipper: ";
    Printer<float>::stream(s, indent + "  ", v.flipper);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TELEOP_MESSAGE_ROBOTCMD_H
